[package]
name = "audiophile"
version = "0.1.0"
authors = ["jostein"]
edition = "2018"

[lib]
name = "audiophile"
path = "src/lib.rs"

[dependencies]
glob = "0.3.0"
claxon = "0.4.1"
hound = "3.4.0"
alac = "0.5.0"